// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: student_service.proto

#include "student_service.pb.h"
#include "student_service.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace school {

static const char* StudentService_method_names[] = {
  "/school.StudentService/GetStudent",
  "/school.StudentService/GetStudents",
};

std::unique_ptr< StudentService::Stub> StudentService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< StudentService::Stub> stub(new StudentService::Stub(channel, options));
  return stub;
}

StudentService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_GetStudent_(StudentService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetStudents_(StudentService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status StudentService::Stub::GetStudent(::grpc::ClientContext* context, const ::school::GetStudentRequest& request, ::school::GetStudentResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::school::GetStudentRequest, ::school::GetStudentResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetStudent_, context, request, response);
}

void StudentService::Stub::async::GetStudent(::grpc::ClientContext* context, const ::school::GetStudentRequest* request, ::school::GetStudentResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::school::GetStudentRequest, ::school::GetStudentResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetStudent_, context, request, response, std::move(f));
}

void StudentService::Stub::async::GetStudent(::grpc::ClientContext* context, const ::school::GetStudentRequest* request, ::school::GetStudentResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetStudent_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::school::GetStudentResponse>* StudentService::Stub::PrepareAsyncGetStudentRaw(::grpc::ClientContext* context, const ::school::GetStudentRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::school::GetStudentResponse, ::school::GetStudentRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetStudent_, context, request);
}

::grpc::ClientAsyncResponseReader< ::school::GetStudentResponse>* StudentService::Stub::AsyncGetStudentRaw(::grpc::ClientContext* context, const ::school::GetStudentRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetStudentRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status StudentService::Stub::GetStudents(::grpc::ClientContext* context, const ::school::GetStudentsRequest& request, ::school::GetStudentsResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::school::GetStudentsRequest, ::school::GetStudentsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetStudents_, context, request, response);
}

void StudentService::Stub::async::GetStudents(::grpc::ClientContext* context, const ::school::GetStudentsRequest* request, ::school::GetStudentsResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::school::GetStudentsRequest, ::school::GetStudentsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetStudents_, context, request, response, std::move(f));
}

void StudentService::Stub::async::GetStudents(::grpc::ClientContext* context, const ::school::GetStudentsRequest* request, ::school::GetStudentsResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetStudents_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::school::GetStudentsResponse>* StudentService::Stub::PrepareAsyncGetStudentsRaw(::grpc::ClientContext* context, const ::school::GetStudentsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::school::GetStudentsResponse, ::school::GetStudentsRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetStudents_, context, request);
}

::grpc::ClientAsyncResponseReader< ::school::GetStudentsResponse>* StudentService::Stub::AsyncGetStudentsRaw(::grpc::ClientContext* context, const ::school::GetStudentsRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetStudentsRaw(context, request, cq);
  result->StartCall();
  return result;
}

StudentService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      StudentService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< StudentService::Service, ::school::GetStudentRequest, ::school::GetStudentResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](StudentService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::school::GetStudentRequest* req,
             ::school::GetStudentResponse* resp) {
               return service->GetStudent(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      StudentService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< StudentService::Service, ::school::GetStudentsRequest, ::school::GetStudentsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](StudentService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::school::GetStudentsRequest* req,
             ::school::GetStudentsResponse* resp) {
               return service->GetStudents(ctx, req, resp);
             }, this)));
}

StudentService::Service::~Service() {
}

::grpc::Status StudentService::Service::GetStudent(::grpc::ServerContext* context, const ::school::GetStudentRequest* request, ::school::GetStudentResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status StudentService::Service::GetStudents(::grpc::ServerContext* context, const ::school::GetStudentsRequest* request, ::school::GetStudentsResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace school

