// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: student_service.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_student_5fservice_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_student_5fservice_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_student_5fservice_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_student_5fservice_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_student_5fservice_2eproto;
namespace school {
class GetStudentRequest;
struct GetStudentRequestDefaultTypeInternal;
extern GetStudentRequestDefaultTypeInternal _GetStudentRequest_default_instance_;
class GetStudentResponse;
struct GetStudentResponseDefaultTypeInternal;
extern GetStudentResponseDefaultTypeInternal _GetStudentResponse_default_instance_;
class GetStudentsRequest;
struct GetStudentsRequestDefaultTypeInternal;
extern GetStudentsRequestDefaultTypeInternal _GetStudentsRequest_default_instance_;
class GetStudentsResponse;
struct GetStudentsResponseDefaultTypeInternal;
extern GetStudentsResponseDefaultTypeInternal _GetStudentsResponse_default_instance_;
class Student;
struct StudentDefaultTypeInternal;
extern StudentDefaultTypeInternal _Student_default_instance_;
}  // namespace school
PROTOBUF_NAMESPACE_OPEN
template<> ::school::GetStudentRequest* Arena::CreateMaybeMessage<::school::GetStudentRequest>(Arena*);
template<> ::school::GetStudentResponse* Arena::CreateMaybeMessage<::school::GetStudentResponse>(Arena*);
template<> ::school::GetStudentsRequest* Arena::CreateMaybeMessage<::school::GetStudentsRequest>(Arena*);
template<> ::school::GetStudentsResponse* Arena::CreateMaybeMessage<::school::GetStudentsResponse>(Arena*);
template<> ::school::Student* Arena::CreateMaybeMessage<::school::Student>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace school {

// ===================================================================

class Student final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:school.Student) */ {
 public:
  inline Student() : Student(nullptr) {}
  ~Student() override;
  explicit PROTOBUF_CONSTEXPR Student(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Student(const Student& from);
  Student(Student&& from) noexcept
    : Student() {
    *this = ::std::move(from);
  }

  inline Student& operator=(const Student& from) {
    CopyFrom(from);
    return *this;
  }
  inline Student& operator=(Student&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Student& default_instance() {
    return *internal_default_instance();
  }
  static inline const Student* internal_default_instance() {
    return reinterpret_cast<const Student*>(
               &_Student_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Student& a, Student& b) {
    a.Swap(&b);
  }
  inline void Swap(Student* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Student* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Student* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Student>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Student& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Student& from) {
    Student::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Student* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "school.Student";
  }
  protected:
  explicit Student(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNameFieldNumber = 2,
    kEmailFieldNumber = 4,
    kIdFieldNumber = 1,
    kAgeFieldNumber = 3,
  };
  // string name = 2;
  void clear_name();
  const std::string& name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_name();
  PROTOBUF_NODISCARD std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // string email = 4;
  void clear_email();
  const std::string& email() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_email(ArgT0&& arg0, ArgT... args);
  std::string* mutable_email();
  PROTOBUF_NODISCARD std::string* release_email();
  void set_allocated_email(std::string* email);
  private:
  const std::string& _internal_email() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_email(const std::string& value);
  std::string* _internal_mutable_email();
  public:

  // int32 id = 1;
  void clear_id();
  int32_t id() const;
  void set_id(int32_t value);
  private:
  int32_t _internal_id() const;
  void _internal_set_id(int32_t value);
  public:

  // int32 age = 3;
  void clear_age();
  int32_t age() const;
  void set_age(int32_t value);
  private:
  int32_t _internal_age() const;
  void _internal_set_age(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:school.Student)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr email_;
    int32_t id_;
    int32_t age_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_student_5fservice_2eproto;
};
// -------------------------------------------------------------------

class GetStudentRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:school.GetStudentRequest) */ {
 public:
  inline GetStudentRequest() : GetStudentRequest(nullptr) {}
  ~GetStudentRequest() override;
  explicit PROTOBUF_CONSTEXPR GetStudentRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  GetStudentRequest(const GetStudentRequest& from);
  GetStudentRequest(GetStudentRequest&& from) noexcept
    : GetStudentRequest() {
    *this = ::std::move(from);
  }

  inline GetStudentRequest& operator=(const GetStudentRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline GetStudentRequest& operator=(GetStudentRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GetStudentRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const GetStudentRequest* internal_default_instance() {
    return reinterpret_cast<const GetStudentRequest*>(
               &_GetStudentRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(GetStudentRequest& a, GetStudentRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(GetStudentRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GetStudentRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GetStudentRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<GetStudentRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const GetStudentRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const GetStudentRequest& from) {
    GetStudentRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GetStudentRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "school.GetStudentRequest";
  }
  protected:
  explicit GetStudentRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kStudentIdFieldNumber = 1,
  };
  // int32 student_id = 1;
  void clear_student_id();
  int32_t student_id() const;
  void set_student_id(int32_t value);
  private:
  int32_t _internal_student_id() const;
  void _internal_set_student_id(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:school.GetStudentRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int32_t student_id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_student_5fservice_2eproto;
};
// -------------------------------------------------------------------

class GetStudentResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:school.GetStudentResponse) */ {
 public:
  inline GetStudentResponse() : GetStudentResponse(nullptr) {}
  ~GetStudentResponse() override;
  explicit PROTOBUF_CONSTEXPR GetStudentResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  GetStudentResponse(const GetStudentResponse& from);
  GetStudentResponse(GetStudentResponse&& from) noexcept
    : GetStudentResponse() {
    *this = ::std::move(from);
  }

  inline GetStudentResponse& operator=(const GetStudentResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline GetStudentResponse& operator=(GetStudentResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GetStudentResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const GetStudentResponse* internal_default_instance() {
    return reinterpret_cast<const GetStudentResponse*>(
               &_GetStudentResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(GetStudentResponse& a, GetStudentResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(GetStudentResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GetStudentResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GetStudentResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<GetStudentResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const GetStudentResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const GetStudentResponse& from) {
    GetStudentResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GetStudentResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "school.GetStudentResponse";
  }
  protected:
  explicit GetStudentResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kStudentFieldNumber = 1,
  };
  // .school.Student student = 1;
  bool has_student() const;
  private:
  bool _internal_has_student() const;
  public:
  void clear_student();
  const ::school::Student& student() const;
  PROTOBUF_NODISCARD ::school::Student* release_student();
  ::school::Student* mutable_student();
  void set_allocated_student(::school::Student* student);
  private:
  const ::school::Student& _internal_student() const;
  ::school::Student* _internal_mutable_student();
  public:
  void unsafe_arena_set_allocated_student(
      ::school::Student* student);
  ::school::Student* unsafe_arena_release_student();

  // @@protoc_insertion_point(class_scope:school.GetStudentResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::school::Student* student_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_student_5fservice_2eproto;
};
// -------------------------------------------------------------------

class GetStudentsRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:school.GetStudentsRequest) */ {
 public:
  inline GetStudentsRequest() : GetStudentsRequest(nullptr) {}
  ~GetStudentsRequest() override;
  explicit PROTOBUF_CONSTEXPR GetStudentsRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  GetStudentsRequest(const GetStudentsRequest& from);
  GetStudentsRequest(GetStudentsRequest&& from) noexcept
    : GetStudentsRequest() {
    *this = ::std::move(from);
  }

  inline GetStudentsRequest& operator=(const GetStudentsRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline GetStudentsRequest& operator=(GetStudentsRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GetStudentsRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const GetStudentsRequest* internal_default_instance() {
    return reinterpret_cast<const GetStudentsRequest*>(
               &_GetStudentsRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(GetStudentsRequest& a, GetStudentsRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(GetStudentsRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GetStudentsRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GetStudentsRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<GetStudentsRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const GetStudentsRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const GetStudentsRequest& from) {
    GetStudentsRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GetStudentsRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "school.GetStudentsRequest";
  }
  protected:
  explicit GetStudentsRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kStudentIdsFieldNumber = 1,
  };
  // repeated int32 student_ids = 1;
  int student_ids_size() const;
  private:
  int _internal_student_ids_size() const;
  public:
  void clear_student_ids();
  private:
  int32_t _internal_student_ids(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
      _internal_student_ids() const;
  void _internal_add_student_ids(int32_t value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
      _internal_mutable_student_ids();
  public:
  int32_t student_ids(int index) const;
  void set_student_ids(int index, int32_t value);
  void add_student_ids(int32_t value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
      student_ids() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
      mutable_student_ids();

  // @@protoc_insertion_point(class_scope:school.GetStudentsRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t > student_ids_;
    mutable std::atomic<int> _student_ids_cached_byte_size_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_student_5fservice_2eproto;
};
// -------------------------------------------------------------------

class GetStudentsResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:school.GetStudentsResponse) */ {
 public:
  inline GetStudentsResponse() : GetStudentsResponse(nullptr) {}
  ~GetStudentsResponse() override;
  explicit PROTOBUF_CONSTEXPR GetStudentsResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  GetStudentsResponse(const GetStudentsResponse& from);
  GetStudentsResponse(GetStudentsResponse&& from) noexcept
    : GetStudentsResponse() {
    *this = ::std::move(from);
  }

  inline GetStudentsResponse& operator=(const GetStudentsResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline GetStudentsResponse& operator=(GetStudentsResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GetStudentsResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const GetStudentsResponse* internal_default_instance() {
    return reinterpret_cast<const GetStudentsResponse*>(
               &_GetStudentsResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(GetStudentsResponse& a, GetStudentsResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(GetStudentsResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GetStudentsResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GetStudentsResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<GetStudentsResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const GetStudentsResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const GetStudentsResponse& from) {
    GetStudentsResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GetStudentsResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "school.GetStudentsResponse";
  }
  protected:
  explicit GetStudentsResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kStudentsFieldNumber = 1,
  };
  // repeated .school.Student students = 1;
  int students_size() const;
  private:
  int _internal_students_size() const;
  public:
  void clear_students();
  ::school::Student* mutable_students(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::school::Student >*
      mutable_students();
  private:
  const ::school::Student& _internal_students(int index) const;
  ::school::Student* _internal_add_students();
  public:
  const ::school::Student& students(int index) const;
  ::school::Student* add_students();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::school::Student >&
      students() const;

  // @@protoc_insertion_point(class_scope:school.GetStudentsResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::school::Student > students_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_student_5fservice_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Student

// int32 id = 1;
inline void Student::clear_id() {
  _impl_.id_ = 0;
}
inline int32_t Student::_internal_id() const {
  return _impl_.id_;
}
inline int32_t Student::id() const {
  // @@protoc_insertion_point(field_get:school.Student.id)
  return _internal_id();
}
inline void Student::_internal_set_id(int32_t value) {
  
  _impl_.id_ = value;
}
inline void Student::set_id(int32_t value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:school.Student.id)
}

// string name = 2;
inline void Student::clear_name() {
  _impl_.name_.ClearToEmpty();
}
inline const std::string& Student::name() const {
  // @@protoc_insertion_point(field_get:school.Student.name)
  return _internal_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Student::set_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:school.Student.name)
}
inline std::string* Student::mutable_name() {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:school.Student.name)
  return _s;
}
inline const std::string& Student::_internal_name() const {
  return _impl_.name_.Get();
}
inline void Student::_internal_set_name(const std::string& value) {
  
  _impl_.name_.Set(value, GetArenaForAllocation());
}
inline std::string* Student::_internal_mutable_name() {
  
  return _impl_.name_.Mutable(GetArenaForAllocation());
}
inline std::string* Student::release_name() {
  // @@protoc_insertion_point(field_release:school.Student.name)
  return _impl_.name_.Release();
}
inline void Student::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  _impl_.name_.SetAllocated(name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.name_.IsDefault()) {
    _impl_.name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:school.Student.name)
}

// int32 age = 3;
inline void Student::clear_age() {
  _impl_.age_ = 0;
}
inline int32_t Student::_internal_age() const {
  return _impl_.age_;
}
inline int32_t Student::age() const {
  // @@protoc_insertion_point(field_get:school.Student.age)
  return _internal_age();
}
inline void Student::_internal_set_age(int32_t value) {
  
  _impl_.age_ = value;
}
inline void Student::set_age(int32_t value) {
  _internal_set_age(value);
  // @@protoc_insertion_point(field_set:school.Student.age)
}

// string email = 4;
inline void Student::clear_email() {
  _impl_.email_.ClearToEmpty();
}
inline const std::string& Student::email() const {
  // @@protoc_insertion_point(field_get:school.Student.email)
  return _internal_email();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Student::set_email(ArgT0&& arg0, ArgT... args) {
 
 _impl_.email_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:school.Student.email)
}
inline std::string* Student::mutable_email() {
  std::string* _s = _internal_mutable_email();
  // @@protoc_insertion_point(field_mutable:school.Student.email)
  return _s;
}
inline const std::string& Student::_internal_email() const {
  return _impl_.email_.Get();
}
inline void Student::_internal_set_email(const std::string& value) {
  
  _impl_.email_.Set(value, GetArenaForAllocation());
}
inline std::string* Student::_internal_mutable_email() {
  
  return _impl_.email_.Mutable(GetArenaForAllocation());
}
inline std::string* Student::release_email() {
  // @@protoc_insertion_point(field_release:school.Student.email)
  return _impl_.email_.Release();
}
inline void Student::set_allocated_email(std::string* email) {
  if (email != nullptr) {
    
  } else {
    
  }
  _impl_.email_.SetAllocated(email, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.email_.IsDefault()) {
    _impl_.email_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:school.Student.email)
}

// -------------------------------------------------------------------

// GetStudentRequest

// int32 student_id = 1;
inline void GetStudentRequest::clear_student_id() {
  _impl_.student_id_ = 0;
}
inline int32_t GetStudentRequest::_internal_student_id() const {
  return _impl_.student_id_;
}
inline int32_t GetStudentRequest::student_id() const {
  // @@protoc_insertion_point(field_get:school.GetStudentRequest.student_id)
  return _internal_student_id();
}
inline void GetStudentRequest::_internal_set_student_id(int32_t value) {
  
  _impl_.student_id_ = value;
}
inline void GetStudentRequest::set_student_id(int32_t value) {
  _internal_set_student_id(value);
  // @@protoc_insertion_point(field_set:school.GetStudentRequest.student_id)
}

// -------------------------------------------------------------------

// GetStudentResponse

// .school.Student student = 1;
inline bool GetStudentResponse::_internal_has_student() const {
  return this != internal_default_instance() && _impl_.student_ != nullptr;
}
inline bool GetStudentResponse::has_student() const {
  return _internal_has_student();
}
inline void GetStudentResponse::clear_student() {
  if (GetArenaForAllocation() == nullptr && _impl_.student_ != nullptr) {
    delete _impl_.student_;
  }
  _impl_.student_ = nullptr;
}
inline const ::school::Student& GetStudentResponse::_internal_student() const {
  const ::school::Student* p = _impl_.student_;
  return p != nullptr ? *p : reinterpret_cast<const ::school::Student&>(
      ::school::_Student_default_instance_);
}
inline const ::school::Student& GetStudentResponse::student() const {
  // @@protoc_insertion_point(field_get:school.GetStudentResponse.student)
  return _internal_student();
}
inline void GetStudentResponse::unsafe_arena_set_allocated_student(
    ::school::Student* student) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.student_);
  }
  _impl_.student_ = student;
  if (student) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:school.GetStudentResponse.student)
}
inline ::school::Student* GetStudentResponse::release_student() {
  
  ::school::Student* temp = _impl_.student_;
  _impl_.student_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::school::Student* GetStudentResponse::unsafe_arena_release_student() {
  // @@protoc_insertion_point(field_release:school.GetStudentResponse.student)
  
  ::school::Student* temp = _impl_.student_;
  _impl_.student_ = nullptr;
  return temp;
}
inline ::school::Student* GetStudentResponse::_internal_mutable_student() {
  
  if (_impl_.student_ == nullptr) {
    auto* p = CreateMaybeMessage<::school::Student>(GetArenaForAllocation());
    _impl_.student_ = p;
  }
  return _impl_.student_;
}
inline ::school::Student* GetStudentResponse::mutable_student() {
  ::school::Student* _msg = _internal_mutable_student();
  // @@protoc_insertion_point(field_mutable:school.GetStudentResponse.student)
  return _msg;
}
inline void GetStudentResponse::set_allocated_student(::school::Student* student) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.student_;
  }
  if (student) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(student);
    if (message_arena != submessage_arena) {
      student = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, student, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.student_ = student;
  // @@protoc_insertion_point(field_set_allocated:school.GetStudentResponse.student)
}

// -------------------------------------------------------------------

// GetStudentsRequest

// repeated int32 student_ids = 1;
inline int GetStudentsRequest::_internal_student_ids_size() const {
  return _impl_.student_ids_.size();
}
inline int GetStudentsRequest::student_ids_size() const {
  return _internal_student_ids_size();
}
inline void GetStudentsRequest::clear_student_ids() {
  _impl_.student_ids_.Clear();
}
inline int32_t GetStudentsRequest::_internal_student_ids(int index) const {
  return _impl_.student_ids_.Get(index);
}
inline int32_t GetStudentsRequest::student_ids(int index) const {
  // @@protoc_insertion_point(field_get:school.GetStudentsRequest.student_ids)
  return _internal_student_ids(index);
}
inline void GetStudentsRequest::set_student_ids(int index, int32_t value) {
  _impl_.student_ids_.Set(index, value);
  // @@protoc_insertion_point(field_set:school.GetStudentsRequest.student_ids)
}
inline void GetStudentsRequest::_internal_add_student_ids(int32_t value) {
  _impl_.student_ids_.Add(value);
}
inline void GetStudentsRequest::add_student_ids(int32_t value) {
  _internal_add_student_ids(value);
  // @@protoc_insertion_point(field_add:school.GetStudentsRequest.student_ids)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
GetStudentsRequest::_internal_student_ids() const {
  return _impl_.student_ids_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
GetStudentsRequest::student_ids() const {
  // @@protoc_insertion_point(field_list:school.GetStudentsRequest.student_ids)
  return _internal_student_ids();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
GetStudentsRequest::_internal_mutable_student_ids() {
  return &_impl_.student_ids_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
GetStudentsRequest::mutable_student_ids() {
  // @@protoc_insertion_point(field_mutable_list:school.GetStudentsRequest.student_ids)
  return _internal_mutable_student_ids();
}

// -------------------------------------------------------------------

// GetStudentsResponse

// repeated .school.Student students = 1;
inline int GetStudentsResponse::_internal_students_size() const {
  return _impl_.students_.size();
}
inline int GetStudentsResponse::students_size() const {
  return _internal_students_size();
}
inline void GetStudentsResponse::clear_students() {
  _impl_.students_.Clear();
}
inline ::school::Student* GetStudentsResponse::mutable_students(int index) {
  // @@protoc_insertion_point(field_mutable:school.GetStudentsResponse.students)
  return _impl_.students_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::school::Student >*
GetStudentsResponse::mutable_students() {
  // @@protoc_insertion_point(field_mutable_list:school.GetStudentsResponse.students)
  return &_impl_.students_;
}
inline const ::school::Student& GetStudentsResponse::_internal_students(int index) const {
  return _impl_.students_.Get(index);
}
inline const ::school::Student& GetStudentsResponse::students(int index) const {
  // @@protoc_insertion_point(field_get:school.GetStudentsResponse.students)
  return _internal_students(index);
}
inline ::school::Student* GetStudentsResponse::_internal_add_students() {
  return _impl_.students_.Add();
}
inline ::school::Student* GetStudentsResponse::add_students() {
  ::school::Student* _add = _internal_add_students();
  // @@protoc_insertion_point(field_add:school.GetStudentsResponse.students)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::school::Student >&
GetStudentsResponse::students() const {
  // @@protoc_insertion_point(field_list:school.GetStudentsResponse.students)
  return _impl_.students_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace school

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_student_5fservice_2eproto
