// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: student_service.proto
#ifndef GRPC_student_5fservice_2eproto__INCLUDED
#define GRPC_student_5fservice_2eproto__INCLUDED

#include "student_service.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace school {

class StudentService final {
 public:
  static constexpr char const* service_full_name() {
    return "school.StudentService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status GetStudent(::grpc::ClientContext* context, const ::school::GetStudentRequest& request, ::school::GetStudentResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::school::GetStudentResponse>> AsyncGetStudent(::grpc::ClientContext* context, const ::school::GetStudentRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::school::GetStudentResponse>>(AsyncGetStudentRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::school::GetStudentResponse>> PrepareAsyncGetStudent(::grpc::ClientContext* context, const ::school::GetStudentRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::school::GetStudentResponse>>(PrepareAsyncGetStudentRaw(context, request, cq));
    }
    virtual ::grpc::Status GetStudents(::grpc::ClientContext* context, const ::school::GetStudentsRequest& request, ::school::GetStudentsResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::school::GetStudentsResponse>> AsyncGetStudents(::grpc::ClientContext* context, const ::school::GetStudentsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::school::GetStudentsResponse>>(AsyncGetStudentsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::school::GetStudentsResponse>> PrepareAsyncGetStudents(::grpc::ClientContext* context, const ::school::GetStudentsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::school::GetStudentsResponse>>(PrepareAsyncGetStudentsRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void GetStudent(::grpc::ClientContext* context, const ::school::GetStudentRequest* request, ::school::GetStudentResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetStudent(::grpc::ClientContext* context, const ::school::GetStudentRequest* request, ::school::GetStudentResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void GetStudents(::grpc::ClientContext* context, const ::school::GetStudentsRequest* request, ::school::GetStudentsResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetStudents(::grpc::ClientContext* context, const ::school::GetStudentsRequest* request, ::school::GetStudentsResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::school::GetStudentResponse>* AsyncGetStudentRaw(::grpc::ClientContext* context, const ::school::GetStudentRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::school::GetStudentResponse>* PrepareAsyncGetStudentRaw(::grpc::ClientContext* context, const ::school::GetStudentRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::school::GetStudentsResponse>* AsyncGetStudentsRaw(::grpc::ClientContext* context, const ::school::GetStudentsRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::school::GetStudentsResponse>* PrepareAsyncGetStudentsRaw(::grpc::ClientContext* context, const ::school::GetStudentsRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status GetStudent(::grpc::ClientContext* context, const ::school::GetStudentRequest& request, ::school::GetStudentResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::school::GetStudentResponse>> AsyncGetStudent(::grpc::ClientContext* context, const ::school::GetStudentRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::school::GetStudentResponse>>(AsyncGetStudentRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::school::GetStudentResponse>> PrepareAsyncGetStudent(::grpc::ClientContext* context, const ::school::GetStudentRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::school::GetStudentResponse>>(PrepareAsyncGetStudentRaw(context, request, cq));
    }
    ::grpc::Status GetStudents(::grpc::ClientContext* context, const ::school::GetStudentsRequest& request, ::school::GetStudentsResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::school::GetStudentsResponse>> AsyncGetStudents(::grpc::ClientContext* context, const ::school::GetStudentsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::school::GetStudentsResponse>>(AsyncGetStudentsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::school::GetStudentsResponse>> PrepareAsyncGetStudents(::grpc::ClientContext* context, const ::school::GetStudentsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::school::GetStudentsResponse>>(PrepareAsyncGetStudentsRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void GetStudent(::grpc::ClientContext* context, const ::school::GetStudentRequest* request, ::school::GetStudentResponse* response, std::function<void(::grpc::Status)>) override;
      void GetStudent(::grpc::ClientContext* context, const ::school::GetStudentRequest* request, ::school::GetStudentResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void GetStudents(::grpc::ClientContext* context, const ::school::GetStudentsRequest* request, ::school::GetStudentsResponse* response, std::function<void(::grpc::Status)>) override;
      void GetStudents(::grpc::ClientContext* context, const ::school::GetStudentsRequest* request, ::school::GetStudentsResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::school::GetStudentResponse>* AsyncGetStudentRaw(::grpc::ClientContext* context, const ::school::GetStudentRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::school::GetStudentResponse>* PrepareAsyncGetStudentRaw(::grpc::ClientContext* context, const ::school::GetStudentRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::school::GetStudentsResponse>* AsyncGetStudentsRaw(::grpc::ClientContext* context, const ::school::GetStudentsRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::school::GetStudentsResponse>* PrepareAsyncGetStudentsRaw(::grpc::ClientContext* context, const ::school::GetStudentsRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GetStudent_;
    const ::grpc::internal::RpcMethod rpcmethod_GetStudents_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status GetStudent(::grpc::ServerContext* context, const ::school::GetStudentRequest* request, ::school::GetStudentResponse* response);
    virtual ::grpc::Status GetStudents(::grpc::ServerContext* context, const ::school::GetStudentsRequest* request, ::school::GetStudentsResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_GetStudent : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetStudent() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GetStudent() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetStudent(::grpc::ServerContext* /*context*/, const ::school::GetStudentRequest* /*request*/, ::school::GetStudentResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetStudent(::grpc::ServerContext* context, ::school::GetStudentRequest* request, ::grpc::ServerAsyncResponseWriter< ::school::GetStudentResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GetStudents : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetStudents() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_GetStudents() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetStudents(::grpc::ServerContext* /*context*/, const ::school::GetStudentsRequest* /*request*/, ::school::GetStudentsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetStudents(::grpc::ServerContext* context, ::school::GetStudentsRequest* request, ::grpc::ServerAsyncResponseWriter< ::school::GetStudentsResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GetStudent<WithAsyncMethod_GetStudents<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_GetStudent : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetStudent() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::school::GetStudentRequest, ::school::GetStudentResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::school::GetStudentRequest* request, ::school::GetStudentResponse* response) { return this->GetStudent(context, request, response); }));}
    void SetMessageAllocatorFor_GetStudent(
        ::grpc::MessageAllocator< ::school::GetStudentRequest, ::school::GetStudentResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::school::GetStudentRequest, ::school::GetStudentResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetStudent() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetStudent(::grpc::ServerContext* /*context*/, const ::school::GetStudentRequest* /*request*/, ::school::GetStudentResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetStudent(
      ::grpc::CallbackServerContext* /*context*/, const ::school::GetStudentRequest* /*request*/, ::school::GetStudentResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_GetStudents : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetStudents() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::school::GetStudentsRequest, ::school::GetStudentsResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::school::GetStudentsRequest* request, ::school::GetStudentsResponse* response) { return this->GetStudents(context, request, response); }));}
    void SetMessageAllocatorFor_GetStudents(
        ::grpc::MessageAllocator< ::school::GetStudentsRequest, ::school::GetStudentsResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::school::GetStudentsRequest, ::school::GetStudentsResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetStudents() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetStudents(::grpc::ServerContext* /*context*/, const ::school::GetStudentsRequest* /*request*/, ::school::GetStudentsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetStudents(
      ::grpc::CallbackServerContext* /*context*/, const ::school::GetStudentsRequest* /*request*/, ::school::GetStudentsResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_GetStudent<WithCallbackMethod_GetStudents<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_GetStudent : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetStudent() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GetStudent() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetStudent(::grpc::ServerContext* /*context*/, const ::school::GetStudentRequest* /*request*/, ::school::GetStudentResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GetStudents : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetStudents() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_GetStudents() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetStudents(::grpc::ServerContext* /*context*/, const ::school::GetStudentsRequest* /*request*/, ::school::GetStudentsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetStudent : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetStudent() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_GetStudent() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetStudent(::grpc::ServerContext* /*context*/, const ::school::GetStudentRequest* /*request*/, ::school::GetStudentResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetStudent(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetStudents : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetStudents() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_GetStudents() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetStudents(::grpc::ServerContext* /*context*/, const ::school::GetStudentsRequest* /*request*/, ::school::GetStudentsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetStudents(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetStudent : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetStudent() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetStudent(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetStudent() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetStudent(::grpc::ServerContext* /*context*/, const ::school::GetStudentRequest* /*request*/, ::school::GetStudentResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetStudent(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetStudents : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetStudents() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetStudents(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetStudents() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetStudents(::grpc::ServerContext* /*context*/, const ::school::GetStudentsRequest* /*request*/, ::school::GetStudentsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetStudents(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetStudent : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetStudent() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::school::GetStudentRequest, ::school::GetStudentResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::school::GetStudentRequest, ::school::GetStudentResponse>* streamer) {
                       return this->StreamedGetStudent(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetStudent() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetStudent(::grpc::ServerContext* /*context*/, const ::school::GetStudentRequest* /*request*/, ::school::GetStudentResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetStudent(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::school::GetStudentRequest,::school::GetStudentResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetStudents : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetStudents() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::school::GetStudentsRequest, ::school::GetStudentsResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::school::GetStudentsRequest, ::school::GetStudentsResponse>* streamer) {
                       return this->StreamedGetStudents(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetStudents() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetStudents(::grpc::ServerContext* /*context*/, const ::school::GetStudentsRequest* /*request*/, ::school::GetStudentsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetStudents(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::school::GetStudentsRequest,::school::GetStudentsResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_GetStudent<WithStreamedUnaryMethod_GetStudents<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_GetStudent<WithStreamedUnaryMethod_GetStudents<Service > > StreamedService;
};

}  // namespace school


#endif  // GRPC_student_5fservice_2eproto__INCLUDED
