// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_STUDENT_SCHOOL_H_
#define FLATBUFFERS_GENERATED_STUDENT_SCHOOL_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 2 &&
              FLATBUFFERS_VERSION_MINOR == 0 &&
              FLATBUFFERS_VERSION_REVISION == 8,
             "Non-compatible flatbuffers version included");

namespace school {

struct Address;
struct AddressBuilder;

struct Student;
struct StudentBuilder;

struct Address FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef AddressBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CITY = 4,
    VT_STREET = 6
  };
  const flatbuffers::String *city() const {
    return GetPointer<const flatbuffers::String *>(VT_CITY);
  }
  const flatbuffers::String *street() const {
    return GetPointer<const flatbuffers::String *>(VT_STREET);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_CITY) &&
           verifier.VerifyString(city()) &&
           VerifyOffset(verifier, VT_STREET) &&
           verifier.VerifyString(street()) &&
           verifier.EndTable();
  }
};

struct AddressBuilder {
  typedef Address Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_city(flatbuffers::Offset<flatbuffers::String> city) {
    fbb_.AddOffset(Address::VT_CITY, city);
  }
  void add_street(flatbuffers::Offset<flatbuffers::String> street) {
    fbb_.AddOffset(Address::VT_STREET, street);
  }
  explicit AddressBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<Address> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Address>(end);
    return o;
  }
};

inline flatbuffers::Offset<Address> CreateAddress(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::String> city = 0,
    flatbuffers::Offset<flatbuffers::String> street = 0) {
  AddressBuilder builder_(_fbb);
  builder_.add_street(street);
  builder_.add_city(city);
  return builder_.Finish();
}

inline flatbuffers::Offset<Address> CreateAddressDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const char *city = nullptr,
    const char *street = nullptr) {
  auto city__ = city ? _fbb.CreateString(city) : 0;
  auto street__ = street ? _fbb.CreateString(street) : 0;
  return school::CreateAddress(
      _fbb,
      city__,
      street__);
}

struct Student FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef StudentBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_NAME = 6,
    VT_AGE = 8,
    VT_ADDRESS = 10,
    VT_COURSES = 12
  };
  int32_t id() const {
    return GetField<int32_t>(VT_ID, 0);
  }
  const flatbuffers::String *name() const {
    return GetPointer<const flatbuffers::String *>(VT_NAME);
  }
  int32_t age() const {
    return GetField<int32_t>(VT_AGE, 0);
  }
  const school::Address *address() const {
    return GetPointer<const school::Address *>(VT_ADDRESS);
  }
  const flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>> *courses() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>> *>(VT_COURSES);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_ID, 4) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyField<int32_t>(verifier, VT_AGE, 4) &&
           VerifyOffset(verifier, VT_ADDRESS) &&
           verifier.VerifyTable(address()) &&
           VerifyOffset(verifier, VT_COURSES) &&
           verifier.VerifyVector(courses()) &&
           verifier.VerifyVectorOfStrings(courses()) &&
           verifier.EndTable();
  }
};

struct StudentBuilder {
  typedef Student Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_id(int32_t id) {
    fbb_.AddElement<int32_t>(Student::VT_ID, id, 0);
  }
  void add_name(flatbuffers::Offset<flatbuffers::String> name) {
    fbb_.AddOffset(Student::VT_NAME, name);
  }
  void add_age(int32_t age) {
    fbb_.AddElement<int32_t>(Student::VT_AGE, age, 0);
  }
  void add_address(flatbuffers::Offset<school::Address> address) {
    fbb_.AddOffset(Student::VT_ADDRESS, address);
  }
  void add_courses(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>>> courses) {
    fbb_.AddOffset(Student::VT_COURSES, courses);
  }
  explicit StudentBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<Student> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Student>(end);
    return o;
  }
};

inline flatbuffers::Offset<Student> CreateStudent(
    flatbuffers::FlatBufferBuilder &_fbb,
    int32_t id = 0,
    flatbuffers::Offset<flatbuffers::String> name = 0,
    int32_t age = 0,
    flatbuffers::Offset<school::Address> address = 0,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>>> courses = 0) {
  StudentBuilder builder_(_fbb);
  builder_.add_courses(courses);
  builder_.add_address(address);
  builder_.add_age(age);
  builder_.add_name(name);
  builder_.add_id(id);
  return builder_.Finish();
}

inline flatbuffers::Offset<Student> CreateStudentDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    int32_t id = 0,
    const char *name = nullptr,
    int32_t age = 0,
    flatbuffers::Offset<school::Address> address = 0,
    const std::vector<flatbuffers::Offset<flatbuffers::String>> *courses = nullptr) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  auto courses__ = courses ? _fbb.CreateVector<flatbuffers::Offset<flatbuffers::String>>(*courses) : 0;
  return school::CreateStudent(
      _fbb,
      id,
      name__,
      age,
      address,
      courses__);
}

inline const school::Student *GetStudent(const void *buf) {
  return flatbuffers::GetRoot<school::Student>(buf);
}

inline const school::Student *GetSizePrefixedStudent(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<school::Student>(buf);
}

inline bool VerifyStudentBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<school::Student>(nullptr);
}

inline bool VerifySizePrefixedStudentBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<school::Student>(nullptr);
}

inline void FinishStudentBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<school::Student> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedStudentBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<school::Student> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace school

#endif  // FLATBUFFERS_GENERATED_STUDENT_SCHOOL_H_
