// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: student.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_student_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_student_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/map.h>  // IWYU pragma: export
#include <google/protobuf/map_entry.h>
#include <google/protobuf/map_field_inl.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_student_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_student_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_student_2eproto;
namespace school {
class Address;
struct AddressDefaultTypeInternal;
extern AddressDefaultTypeInternal _Address_default_instance_;
class Student;
struct StudentDefaultTypeInternal;
extern StudentDefaultTypeInternal _Student_default_instance_;
class Student_ScoresEntry_DoNotUse;
struct Student_ScoresEntry_DoNotUseDefaultTypeInternal;
extern Student_ScoresEntry_DoNotUseDefaultTypeInternal _Student_ScoresEntry_DoNotUse_default_instance_;
}  // namespace school
PROTOBUF_NAMESPACE_OPEN
template<> ::school::Address* Arena::CreateMaybeMessage<::school::Address>(Arena*);
template<> ::school::Student* Arena::CreateMaybeMessage<::school::Student>(Arena*);
template<> ::school::Student_ScoresEntry_DoNotUse* Arena::CreateMaybeMessage<::school::Student_ScoresEntry_DoNotUse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace school {

enum Gender : int {
  UNKNOWN = 0,
  MALE = 1,
  FEMALE = 2,
  Gender_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  Gender_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool Gender_IsValid(int value);
constexpr Gender Gender_MIN = UNKNOWN;
constexpr Gender Gender_MAX = FEMALE;
constexpr int Gender_ARRAYSIZE = Gender_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* Gender_descriptor();
template<typename T>
inline const std::string& Gender_Name(T enum_t_value) {
  static_assert(::std::is_same<T, Gender>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function Gender_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    Gender_descriptor(), enum_t_value);
}
inline bool Gender_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, Gender* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<Gender>(
    Gender_descriptor(), name, value);
}
// ===================================================================

class Address final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:school.Address) */ {
 public:
  inline Address() : Address(nullptr) {}
  ~Address() override;
  explicit PROTOBUF_CONSTEXPR Address(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Address(const Address& from);
  Address(Address&& from) noexcept
    : Address() {
    *this = ::std::move(from);
  }

  inline Address& operator=(const Address& from) {
    CopyFrom(from);
    return *this;
  }
  inline Address& operator=(Address&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Address& default_instance() {
    return *internal_default_instance();
  }
  static inline const Address* internal_default_instance() {
    return reinterpret_cast<const Address*>(
               &_Address_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Address& a, Address& b) {
    a.Swap(&b);
  }
  inline void Swap(Address* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Address* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Address* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Address>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Address& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Address& from) {
    Address::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Address* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "school.Address";
  }
  protected:
  explicit Address(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kCityFieldNumber = 1,
    kStreetFieldNumber = 2,
    kZipCodeFieldNumber = 3,
  };
  // string city = 1;
  void clear_city();
  const std::string& city() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_city(ArgT0&& arg0, ArgT... args);
  std::string* mutable_city();
  PROTOBUF_NODISCARD std::string* release_city();
  void set_allocated_city(std::string* city);
  private:
  const std::string& _internal_city() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_city(const std::string& value);
  std::string* _internal_mutable_city();
  public:

  // string street = 2;
  void clear_street();
  const std::string& street() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_street(ArgT0&& arg0, ArgT... args);
  std::string* mutable_street();
  PROTOBUF_NODISCARD std::string* release_street();
  void set_allocated_street(std::string* street);
  private:
  const std::string& _internal_street() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_street(const std::string& value);
  std::string* _internal_mutable_street();
  public:

  // string zip_code = 3;
  void clear_zip_code();
  const std::string& zip_code() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_zip_code(ArgT0&& arg0, ArgT... args);
  std::string* mutable_zip_code();
  PROTOBUF_NODISCARD std::string* release_zip_code();
  void set_allocated_zip_code(std::string* zip_code);
  private:
  const std::string& _internal_zip_code() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_zip_code(const std::string& value);
  std::string* _internal_mutable_zip_code();
  public:

  // @@protoc_insertion_point(class_scope:school.Address)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr city_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr street_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr zip_code_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_student_2eproto;
};
// -------------------------------------------------------------------

class Student_ScoresEntry_DoNotUse : public ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<Student_ScoresEntry_DoNotUse, 
    std::string, int32_t,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_INT32> {
public:
  typedef ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<Student_ScoresEntry_DoNotUse, 
    std::string, int32_t,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_INT32> SuperType;
  Student_ScoresEntry_DoNotUse();
  explicit PROTOBUF_CONSTEXPR Student_ScoresEntry_DoNotUse(
      ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);
  explicit Student_ScoresEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void MergeFrom(const Student_ScoresEntry_DoNotUse& other);
  static const Student_ScoresEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const Student_ScoresEntry_DoNotUse*>(&_Student_ScoresEntry_DoNotUse_default_instance_); }
  static bool ValidateKey(std::string* s) {
    return ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(s->data(), static_cast<int>(s->size()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::PARSE, "school.Student.ScoresEntry.key");
 }
  static bool ValidateValue(void*) { return true; }
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  friend struct ::TableStruct_student_2eproto;
};

// -------------------------------------------------------------------

class Student final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:school.Student) */ {
 public:
  inline Student() : Student(nullptr) {}
  ~Student() override;
  explicit PROTOBUF_CONSTEXPR Student(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Student(const Student& from);
  Student(Student&& from) noexcept
    : Student() {
    *this = ::std::move(from);
  }

  inline Student& operator=(const Student& from) {
    CopyFrom(from);
    return *this;
  }
  inline Student& operator=(Student&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Student& default_instance() {
    return *internal_default_instance();
  }
  enum ContactCase {
    kPhone = 9,
    kWechat = 10,
    CONTACT_NOT_SET = 0,
  };

  static inline const Student* internal_default_instance() {
    return reinterpret_cast<const Student*>(
               &_Student_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(Student& a, Student& b) {
    a.Swap(&b);
  }
  inline void Swap(Student* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Student* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Student* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Student>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Student& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Student& from) {
    Student::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Student* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "school.Student";
  }
  protected:
  explicit Student(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  enum : int {
    kCoursesFieldNumber = 7,
    kScoresFieldNumber = 8,
    kNameFieldNumber = 2,
    kEmailFieldNumber = 4,
    kAddressFieldNumber = 6,
    kIdFieldNumber = 1,
    kAgeFieldNumber = 3,
    kGenderFieldNumber = 5,
    kPhoneFieldNumber = 9,
    kWechatFieldNumber = 10,
  };
  // repeated string courses = 7;
  int courses_size() const;
  private:
  int _internal_courses_size() const;
  public:
  void clear_courses();
  const std::string& courses(int index) const;
  std::string* mutable_courses(int index);
  void set_courses(int index, const std::string& value);
  void set_courses(int index, std::string&& value);
  void set_courses(int index, const char* value);
  void set_courses(int index, const char* value, size_t size);
  std::string* add_courses();
  void add_courses(const std::string& value);
  void add_courses(std::string&& value);
  void add_courses(const char* value);
  void add_courses(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& courses() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_courses();
  private:
  const std::string& _internal_courses(int index) const;
  std::string* _internal_add_courses();
  public:

  // map<string, int32> scores = 8;
  int scores_size() const;
  private:
  int _internal_scores_size() const;
  public:
  void clear_scores();
  private:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, int32_t >&
      _internal_scores() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, int32_t >*
      _internal_mutable_scores();
  public:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, int32_t >&
      scores() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, int32_t >*
      mutable_scores();

  // string name = 2;
  void clear_name();
  const std::string& name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_name();
  PROTOBUF_NODISCARD std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // string email = 4;
  void clear_email();
  const std::string& email() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_email(ArgT0&& arg0, ArgT... args);
  std::string* mutable_email();
  PROTOBUF_NODISCARD std::string* release_email();
  void set_allocated_email(std::string* email);
  private:
  const std::string& _internal_email() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_email(const std::string& value);
  std::string* _internal_mutable_email();
  public:

  // .school.Address address = 6;
  bool has_address() const;
  private:
  bool _internal_has_address() const;
  public:
  void clear_address();
  const ::school::Address& address() const;
  PROTOBUF_NODISCARD ::school::Address* release_address();
  ::school::Address* mutable_address();
  void set_allocated_address(::school::Address* address);
  private:
  const ::school::Address& _internal_address() const;
  ::school::Address* _internal_mutable_address();
  public:
  void unsafe_arena_set_allocated_address(
      ::school::Address* address);
  ::school::Address* unsafe_arena_release_address();

  // int32 id = 1;
  void clear_id();
  int32_t id() const;
  void set_id(int32_t value);
  private:
  int32_t _internal_id() const;
  void _internal_set_id(int32_t value);
  public:

  // int32 age = 3;
  void clear_age();
  int32_t age() const;
  void set_age(int32_t value);
  private:
  int32_t _internal_age() const;
  void _internal_set_age(int32_t value);
  public:

  // .school.Gender gender = 5;
  void clear_gender();
  ::school::Gender gender() const;
  void set_gender(::school::Gender value);
  private:
  ::school::Gender _internal_gender() const;
  void _internal_set_gender(::school::Gender value);
  public:

  // string phone = 9;
  bool has_phone() const;
  private:
  bool _internal_has_phone() const;
  public:
  void clear_phone();
  const std::string& phone() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_phone(ArgT0&& arg0, ArgT... args);
  std::string* mutable_phone();
  PROTOBUF_NODISCARD std::string* release_phone();
  void set_allocated_phone(std::string* phone);
  private:
  const std::string& _internal_phone() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_phone(const std::string& value);
  std::string* _internal_mutable_phone();
  public:

  // string wechat = 10;
  bool has_wechat() const;
  private:
  bool _internal_has_wechat() const;
  public:
  void clear_wechat();
  const std::string& wechat() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_wechat(ArgT0&& arg0, ArgT... args);
  std::string* mutable_wechat();
  PROTOBUF_NODISCARD std::string* release_wechat();
  void set_allocated_wechat(std::string* wechat);
  private:
  const std::string& _internal_wechat() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_wechat(const std::string& value);
  std::string* _internal_mutable_wechat();
  public:

  void clear_contact();
  ContactCase contact_case() const;
  // @@protoc_insertion_point(class_scope:school.Student)
 private:
  class _Internal;
  void set_has_phone();
  void set_has_wechat();

  inline bool has_contact() const;
  inline void clear_has_contact();

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> courses_;
    ::PROTOBUF_NAMESPACE_ID::internal::MapField<
        Student_ScoresEntry_DoNotUse,
        std::string, int32_t,
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_INT32> scores_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr email_;
    ::school::Address* address_;
    int32_t id_;
    int32_t age_;
    int gender_;
    union ContactUnion {
      constexpr ContactUnion() : _constinit_{} {}
        ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized _constinit_;
      ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr phone_;
      ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr wechat_;
    } contact_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    uint32_t _oneof_case_[1];

  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_student_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Address

// string city = 1;
inline void Address::clear_city() {
  _impl_.city_.ClearToEmpty();
}
inline const std::string& Address::city() const {
  // @@protoc_insertion_point(field_get:school.Address.city)
  return _internal_city();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Address::set_city(ArgT0&& arg0, ArgT... args) {
 
 _impl_.city_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:school.Address.city)
}
inline std::string* Address::mutable_city() {
  std::string* _s = _internal_mutable_city();
  // @@protoc_insertion_point(field_mutable:school.Address.city)
  return _s;
}
inline const std::string& Address::_internal_city() const {
  return _impl_.city_.Get();
}
inline void Address::_internal_set_city(const std::string& value) {
  
  _impl_.city_.Set(value, GetArenaForAllocation());
}
inline std::string* Address::_internal_mutable_city() {
  
  return _impl_.city_.Mutable(GetArenaForAllocation());
}
inline std::string* Address::release_city() {
  // @@protoc_insertion_point(field_release:school.Address.city)
  return _impl_.city_.Release();
}
inline void Address::set_allocated_city(std::string* city) {
  if (city != nullptr) {
    
  } else {
    
  }
  _impl_.city_.SetAllocated(city, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.city_.IsDefault()) {
    _impl_.city_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:school.Address.city)
}

// string street = 2;
inline void Address::clear_street() {
  _impl_.street_.ClearToEmpty();
}
inline const std::string& Address::street() const {
  // @@protoc_insertion_point(field_get:school.Address.street)
  return _internal_street();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Address::set_street(ArgT0&& arg0, ArgT... args) {
 
 _impl_.street_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:school.Address.street)
}
inline std::string* Address::mutable_street() {
  std::string* _s = _internal_mutable_street();
  // @@protoc_insertion_point(field_mutable:school.Address.street)
  return _s;
}
inline const std::string& Address::_internal_street() const {
  return _impl_.street_.Get();
}
inline void Address::_internal_set_street(const std::string& value) {
  
  _impl_.street_.Set(value, GetArenaForAllocation());
}
inline std::string* Address::_internal_mutable_street() {
  
  return _impl_.street_.Mutable(GetArenaForAllocation());
}
inline std::string* Address::release_street() {
  // @@protoc_insertion_point(field_release:school.Address.street)
  return _impl_.street_.Release();
}
inline void Address::set_allocated_street(std::string* street) {
  if (street != nullptr) {
    
  } else {
    
  }
  _impl_.street_.SetAllocated(street, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.street_.IsDefault()) {
    _impl_.street_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:school.Address.street)
}

// string zip_code = 3;
inline void Address::clear_zip_code() {
  _impl_.zip_code_.ClearToEmpty();
}
inline const std::string& Address::zip_code() const {
  // @@protoc_insertion_point(field_get:school.Address.zip_code)
  return _internal_zip_code();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Address::set_zip_code(ArgT0&& arg0, ArgT... args) {
 
 _impl_.zip_code_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:school.Address.zip_code)
}
inline std::string* Address::mutable_zip_code() {
  std::string* _s = _internal_mutable_zip_code();
  // @@protoc_insertion_point(field_mutable:school.Address.zip_code)
  return _s;
}
inline const std::string& Address::_internal_zip_code() const {
  return _impl_.zip_code_.Get();
}
inline void Address::_internal_set_zip_code(const std::string& value) {
  
  _impl_.zip_code_.Set(value, GetArenaForAllocation());
}
inline std::string* Address::_internal_mutable_zip_code() {
  
  return _impl_.zip_code_.Mutable(GetArenaForAllocation());
}
inline std::string* Address::release_zip_code() {
  // @@protoc_insertion_point(field_release:school.Address.zip_code)
  return _impl_.zip_code_.Release();
}
inline void Address::set_allocated_zip_code(std::string* zip_code) {
  if (zip_code != nullptr) {
    
  } else {
    
  }
  _impl_.zip_code_.SetAllocated(zip_code, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.zip_code_.IsDefault()) {
    _impl_.zip_code_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:school.Address.zip_code)
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// Student

// int32 id = 1;
inline void Student::clear_id() {
  _impl_.id_ = 0;
}
inline int32_t Student::_internal_id() const {
  return _impl_.id_;
}
inline int32_t Student::id() const {
  // @@protoc_insertion_point(field_get:school.Student.id)
  return _internal_id();
}
inline void Student::_internal_set_id(int32_t value) {
  
  _impl_.id_ = value;
}
inline void Student::set_id(int32_t value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:school.Student.id)
}

// string name = 2;
inline void Student::clear_name() {
  _impl_.name_.ClearToEmpty();
}
inline const std::string& Student::name() const {
  // @@protoc_insertion_point(field_get:school.Student.name)
  return _internal_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Student::set_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:school.Student.name)
}
inline std::string* Student::mutable_name() {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:school.Student.name)
  return _s;
}
inline const std::string& Student::_internal_name() const {
  return _impl_.name_.Get();
}
inline void Student::_internal_set_name(const std::string& value) {
  
  _impl_.name_.Set(value, GetArenaForAllocation());
}
inline std::string* Student::_internal_mutable_name() {
  
  return _impl_.name_.Mutable(GetArenaForAllocation());
}
inline std::string* Student::release_name() {
  // @@protoc_insertion_point(field_release:school.Student.name)
  return _impl_.name_.Release();
}
inline void Student::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  _impl_.name_.SetAllocated(name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.name_.IsDefault()) {
    _impl_.name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:school.Student.name)
}

// int32 age = 3;
inline void Student::clear_age() {
  _impl_.age_ = 0;
}
inline int32_t Student::_internal_age() const {
  return _impl_.age_;
}
inline int32_t Student::age() const {
  // @@protoc_insertion_point(field_get:school.Student.age)
  return _internal_age();
}
inline void Student::_internal_set_age(int32_t value) {
  
  _impl_.age_ = value;
}
inline void Student::set_age(int32_t value) {
  _internal_set_age(value);
  // @@protoc_insertion_point(field_set:school.Student.age)
}

// string email = 4;
inline void Student::clear_email() {
  _impl_.email_.ClearToEmpty();
}
inline const std::string& Student::email() const {
  // @@protoc_insertion_point(field_get:school.Student.email)
  return _internal_email();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Student::set_email(ArgT0&& arg0, ArgT... args) {
 
 _impl_.email_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:school.Student.email)
}
inline std::string* Student::mutable_email() {
  std::string* _s = _internal_mutable_email();
  // @@protoc_insertion_point(field_mutable:school.Student.email)
  return _s;
}
inline const std::string& Student::_internal_email() const {
  return _impl_.email_.Get();
}
inline void Student::_internal_set_email(const std::string& value) {
  
  _impl_.email_.Set(value, GetArenaForAllocation());
}
inline std::string* Student::_internal_mutable_email() {
  
  return _impl_.email_.Mutable(GetArenaForAllocation());
}
inline std::string* Student::release_email() {
  // @@protoc_insertion_point(field_release:school.Student.email)
  return _impl_.email_.Release();
}
inline void Student::set_allocated_email(std::string* email) {
  if (email != nullptr) {
    
  } else {
    
  }
  _impl_.email_.SetAllocated(email, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.email_.IsDefault()) {
    _impl_.email_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:school.Student.email)
}

// .school.Gender gender = 5;
inline void Student::clear_gender() {
  _impl_.gender_ = 0;
}
inline ::school::Gender Student::_internal_gender() const {
  return static_cast< ::school::Gender >(_impl_.gender_);
}
inline ::school::Gender Student::gender() const {
  // @@protoc_insertion_point(field_get:school.Student.gender)
  return _internal_gender();
}
inline void Student::_internal_set_gender(::school::Gender value) {
  
  _impl_.gender_ = value;
}
inline void Student::set_gender(::school::Gender value) {
  _internal_set_gender(value);
  // @@protoc_insertion_point(field_set:school.Student.gender)
}

// .school.Address address = 6;
inline bool Student::_internal_has_address() const {
  return this != internal_default_instance() && _impl_.address_ != nullptr;
}
inline bool Student::has_address() const {
  return _internal_has_address();
}
inline void Student::clear_address() {
  if (GetArenaForAllocation() == nullptr && _impl_.address_ != nullptr) {
    delete _impl_.address_;
  }
  _impl_.address_ = nullptr;
}
inline const ::school::Address& Student::_internal_address() const {
  const ::school::Address* p = _impl_.address_;
  return p != nullptr ? *p : reinterpret_cast<const ::school::Address&>(
      ::school::_Address_default_instance_);
}
inline const ::school::Address& Student::address() const {
  // @@protoc_insertion_point(field_get:school.Student.address)
  return _internal_address();
}
inline void Student::unsafe_arena_set_allocated_address(
    ::school::Address* address) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.address_);
  }
  _impl_.address_ = address;
  if (address) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:school.Student.address)
}
inline ::school::Address* Student::release_address() {
  
  ::school::Address* temp = _impl_.address_;
  _impl_.address_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::school::Address* Student::unsafe_arena_release_address() {
  // @@protoc_insertion_point(field_release:school.Student.address)
  
  ::school::Address* temp = _impl_.address_;
  _impl_.address_ = nullptr;
  return temp;
}
inline ::school::Address* Student::_internal_mutable_address() {
  
  if (_impl_.address_ == nullptr) {
    auto* p = CreateMaybeMessage<::school::Address>(GetArenaForAllocation());
    _impl_.address_ = p;
  }
  return _impl_.address_;
}
inline ::school::Address* Student::mutable_address() {
  ::school::Address* _msg = _internal_mutable_address();
  // @@protoc_insertion_point(field_mutable:school.Student.address)
  return _msg;
}
inline void Student::set_allocated_address(::school::Address* address) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.address_;
  }
  if (address) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(address);
    if (message_arena != submessage_arena) {
      address = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, address, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.address_ = address;
  // @@protoc_insertion_point(field_set_allocated:school.Student.address)
}

// repeated string courses = 7;
inline int Student::_internal_courses_size() const {
  return _impl_.courses_.size();
}
inline int Student::courses_size() const {
  return _internal_courses_size();
}
inline void Student::clear_courses() {
  _impl_.courses_.Clear();
}
inline std::string* Student::add_courses() {
  std::string* _s = _internal_add_courses();
  // @@protoc_insertion_point(field_add_mutable:school.Student.courses)
  return _s;
}
inline const std::string& Student::_internal_courses(int index) const {
  return _impl_.courses_.Get(index);
}
inline const std::string& Student::courses(int index) const {
  // @@protoc_insertion_point(field_get:school.Student.courses)
  return _internal_courses(index);
}
inline std::string* Student::mutable_courses(int index) {
  // @@protoc_insertion_point(field_mutable:school.Student.courses)
  return _impl_.courses_.Mutable(index);
}
inline void Student::set_courses(int index, const std::string& value) {
  _impl_.courses_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set:school.Student.courses)
}
inline void Student::set_courses(int index, std::string&& value) {
  _impl_.courses_.Mutable(index)->assign(std::move(value));
  // @@protoc_insertion_point(field_set:school.Student.courses)
}
inline void Student::set_courses(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _impl_.courses_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:school.Student.courses)
}
inline void Student::set_courses(int index, const char* value, size_t size) {
  _impl_.courses_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:school.Student.courses)
}
inline std::string* Student::_internal_add_courses() {
  return _impl_.courses_.Add();
}
inline void Student::add_courses(const std::string& value) {
  _impl_.courses_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:school.Student.courses)
}
inline void Student::add_courses(std::string&& value) {
  _impl_.courses_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:school.Student.courses)
}
inline void Student::add_courses(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _impl_.courses_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:school.Student.courses)
}
inline void Student::add_courses(const char* value, size_t size) {
  _impl_.courses_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:school.Student.courses)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
Student::courses() const {
  // @@protoc_insertion_point(field_list:school.Student.courses)
  return _impl_.courses_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
Student::mutable_courses() {
  // @@protoc_insertion_point(field_mutable_list:school.Student.courses)
  return &_impl_.courses_;
}

// map<string, int32> scores = 8;
inline int Student::_internal_scores_size() const {
  return _impl_.scores_.size();
}
inline int Student::scores_size() const {
  return _internal_scores_size();
}
inline void Student::clear_scores() {
  _impl_.scores_.Clear();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, int32_t >&
Student::_internal_scores() const {
  return _impl_.scores_.GetMap();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, int32_t >&
Student::scores() const {
  // @@protoc_insertion_point(field_map:school.Student.scores)
  return _internal_scores();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, int32_t >*
Student::_internal_mutable_scores() {
  return _impl_.scores_.MutableMap();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, int32_t >*
Student::mutable_scores() {
  // @@protoc_insertion_point(field_mutable_map:school.Student.scores)
  return _internal_mutable_scores();
}

// string phone = 9;
inline bool Student::_internal_has_phone() const {
  return contact_case() == kPhone;
}
inline bool Student::has_phone() const {
  return _internal_has_phone();
}
inline void Student::set_has_phone() {
  _impl_._oneof_case_[0] = kPhone;
}
inline void Student::clear_phone() {
  if (_internal_has_phone()) {
    _impl_.contact_.phone_.Destroy();
    clear_has_contact();
  }
}
inline const std::string& Student::phone() const {
  // @@protoc_insertion_point(field_get:school.Student.phone)
  return _internal_phone();
}
template <typename ArgT0, typename... ArgT>
inline void Student::set_phone(ArgT0&& arg0, ArgT... args) {
  if (!_internal_has_phone()) {
    clear_contact();
    set_has_phone();
    _impl_.contact_.phone_.InitDefault();
  }
  _impl_.contact_.phone_.Set( static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:school.Student.phone)
}
inline std::string* Student::mutable_phone() {
  std::string* _s = _internal_mutable_phone();
  // @@protoc_insertion_point(field_mutable:school.Student.phone)
  return _s;
}
inline const std::string& Student::_internal_phone() const {
  if (_internal_has_phone()) {
    return _impl_.contact_.phone_.Get();
  }
  return ::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited();
}
inline void Student::_internal_set_phone(const std::string& value) {
  if (!_internal_has_phone()) {
    clear_contact();
    set_has_phone();
    _impl_.contact_.phone_.InitDefault();
  }
  _impl_.contact_.phone_.Set(value, GetArenaForAllocation());
}
inline std::string* Student::_internal_mutable_phone() {
  if (!_internal_has_phone()) {
    clear_contact();
    set_has_phone();
    _impl_.contact_.phone_.InitDefault();
  }
  return _impl_.contact_.phone_.Mutable(      GetArenaForAllocation());
}
inline std::string* Student::release_phone() {
  // @@protoc_insertion_point(field_release:school.Student.phone)
  if (_internal_has_phone()) {
    clear_has_contact();
    return _impl_.contact_.phone_.Release();
  } else {
    return nullptr;
  }
}
inline void Student::set_allocated_phone(std::string* phone) {
  if (has_contact()) {
    clear_contact();
  }
  if (phone != nullptr) {
    set_has_phone();
    _impl_.contact_.phone_.InitAllocated(phone, GetArenaForAllocation());
  }
  // @@protoc_insertion_point(field_set_allocated:school.Student.phone)
}

// string wechat = 10;
inline bool Student::_internal_has_wechat() const {
  return contact_case() == kWechat;
}
inline bool Student::has_wechat() const {
  return _internal_has_wechat();
}
inline void Student::set_has_wechat() {
  _impl_._oneof_case_[0] = kWechat;
}
inline void Student::clear_wechat() {
  if (_internal_has_wechat()) {
    _impl_.contact_.wechat_.Destroy();
    clear_has_contact();
  }
}
inline const std::string& Student::wechat() const {
  // @@protoc_insertion_point(field_get:school.Student.wechat)
  return _internal_wechat();
}
template <typename ArgT0, typename... ArgT>
inline void Student::set_wechat(ArgT0&& arg0, ArgT... args) {
  if (!_internal_has_wechat()) {
    clear_contact();
    set_has_wechat();
    _impl_.contact_.wechat_.InitDefault();
  }
  _impl_.contact_.wechat_.Set( static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:school.Student.wechat)
}
inline std::string* Student::mutable_wechat() {
  std::string* _s = _internal_mutable_wechat();
  // @@protoc_insertion_point(field_mutable:school.Student.wechat)
  return _s;
}
inline const std::string& Student::_internal_wechat() const {
  if (_internal_has_wechat()) {
    return _impl_.contact_.wechat_.Get();
  }
  return ::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited();
}
inline void Student::_internal_set_wechat(const std::string& value) {
  if (!_internal_has_wechat()) {
    clear_contact();
    set_has_wechat();
    _impl_.contact_.wechat_.InitDefault();
  }
  _impl_.contact_.wechat_.Set(value, GetArenaForAllocation());
}
inline std::string* Student::_internal_mutable_wechat() {
  if (!_internal_has_wechat()) {
    clear_contact();
    set_has_wechat();
    _impl_.contact_.wechat_.InitDefault();
  }
  return _impl_.contact_.wechat_.Mutable(      GetArenaForAllocation());
}
inline std::string* Student::release_wechat() {
  // @@protoc_insertion_point(field_release:school.Student.wechat)
  if (_internal_has_wechat()) {
    clear_has_contact();
    return _impl_.contact_.wechat_.Release();
  } else {
    return nullptr;
  }
}
inline void Student::set_allocated_wechat(std::string* wechat) {
  if (has_contact()) {
    clear_contact();
  }
  if (wechat != nullptr) {
    set_has_wechat();
    _impl_.contact_.wechat_.InitAllocated(wechat, GetArenaForAllocation());
  }
  // @@protoc_insertion_point(field_set_allocated:school.Student.wechat)
}

inline bool Student::has_contact() const {
  return contact_case() != CONTACT_NOT_SET;
}
inline void Student::clear_has_contact() {
  _impl_._oneof_case_[0] = CONTACT_NOT_SET;
}
inline Student::ContactCase Student::contact_case() const {
  return Student::ContactCase(_impl_._oneof_case_[0]);
}
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace school

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::school::Gender> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::school::Gender>() {
  return ::school::Gender_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_student_2eproto
